(define (cube x) (* x x x))
(define (p x) (- (* 3 x) (* 4 (cube x))))
(define (sine angle)
  (if (not (> (abs angle) 0.1))
      angle
      (p (sine (/ angle 3.0)))))

(sine 1.0)
(sine 2)
(sine 3)
(sine 0)

;; a) How many times is the procedure p applied when (sine 12.15) is evaluated?
;; assume n.
;; then 12.15 / 3^n <= 0.1
;; ==> n >= 4.95
;; so, the lowest of n is 5.


;; b) What is the order of growth in space and number of steps(as a function of a)
;;    used by the process generated by the sine procedure when (sine a) is evaluated?
;; both are log(a, 3)
